### ISSUE TITLE
Auto link when github issue comment

### ISSUE THREAD

**Issue by anencore94** [hunhoon21/github-issue-to-shortcut-story#1]
https://github.com/hunhoon21/github-issue-to-shortcut-story/blob/33050490254b689bce5f33a44391aaaa0b350709/src/main.py#L38

1) `{shortcut_story_id}` 대신 `[sc-{shortcut_story_id}]` 로 하고 해당 repo 에 https://help.shortcut.com/hc/en-us/articles/360045141431-GitHub-Autolinking-with-Shortcut-Stories 를 켜두거나,

2) `{shortcut_story_id}` 대신, `[{shortcut_story_id}](https://app.shortcut.com/makinarocks/story/{shortcut_story_id})` 로 해두면

github comment 에서 shortcut 링크를 바로 클릭할 수 있게 되어 더 편하게 사용할 수 있을 것 같습니다.

---
또한, 반대로 story 를 create 할 때, [body](https://github.com/hunhoon21/github-issue-to-shortcut-story/blob/33050490254b689bce5f33a44391aaaa0b350709/src/main.py#L27) 의 맨 마지막 부분에 `related github issue : "https://github.com/<ORG_NAME>/<REPO_NAME>/<ISSUE_NUM>"` 을 추가해주면 서로 간의 링크를 더 쉽게 타고갈 수 있을 것 같습니다.

**Comment by hunhoon21** [comment]
autolink 너무 좋네요 :) 좋은 제안 감사합니다!

**Comment by hunhoon21** [comment]
body 말고 코멘트로
```
This story is related to github issue [#<number>](link)
```
이렇게 다는것도 좋겠네요!

**Comment by anencore94** [comment]
코멘트는 생각 못했네요! 그게 더 좋을 것 같습니다! @hunhoon21

**Comment by anencore94** [comment]
코멘트는 생각 못했네요! 그게 더 좋을 것 같습니다! @hunhoon21
